### ISSUE TITLE
Use deep links to Herd-UI pages

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd-mdl#12]
As a Herd-UI user I want to be able to link directly to a Herd-UI page so I can bookmark and/or send links.

Currently both scenarios listed in the acceptance criteria return a 404. We need them to work as documented here:

Acceptance Criteria
* User can enter full URL like herd-ui.com/data-entities/SEC_MARKET_DATA/SecurityData in a new browser session and go directly to that page
* User can be on any Herd-UI page and reload their browser and it will reload and display the same page

Technical Notes:
* Options appear to be:
  * Put Herd-UI on Herd's Apache
  * Put rewrite rules in S3 bucket under CloudFront like https://blog.goguardian.com/nerds/redirects-in-aws-cloudfront
  * Use cloudfront + lambda like https://linuxacademy.com/howtoguides/posts/show/topic/19955-url-rewriting-in-aws-cloudfront 
* Takes apache config like:

```
<IfModule mod_rewrite.c>

  RewriteEngine on

  # -- send bots/spiders/crawlers 404 page not found
  RewriteCond %{HTTP_USER_AGENT} (bot|spider|crawler|search|find|walker) [NC]
  RewriteRule .* - [R=404,L]

  # -- HTTP to HTTPS
  RewriteCond %{HTTP:X-Forwarded-Proto} ^http$
  RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R,L]

  ## custom rule for herdui
  # Rewrite routes to index.html unless they are for specific files
  # Don't rewrite files or directories
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
  RewriteRule ^ - [L]

  # If the requested resource doesn't exist, use index.html
  RewriteRule ^ /index.html


</IfModule>
```

**Comment by sbalkee** [comment]
1. Research the above solutions

**Comment by kenisteward** [comment]
You can mark this as closed when the the first solution is implemented in the CFT for when cloudfront is not used with only an s3 static web page configuration.

The solution is to simply set the Error Page for s3 static web page to index.html

The solution for cloudfront is already implemented inside the CFT for Cloudfront which was to set a custom error response for 404's as index.html/200.

**Comment by aniruddhadas9** [comment]
@kenisteward But we don't want to show them error. we will redirect them to the page where they come from. Like if they are trying to access `baseUrl/data-entities/nsx/xxx` they need to be go to that page as well. Will configuring `404's as index.html/200` will redirect to `data-entities/nsx/xxx` if they came from that page?

**Comment by kenisteward** [comment]
@aniruddhadas9 the error won't be shown with the config i gave.

**Comment by nateiam** [comment]
Maybe someone should include a functional test with the PR.Agree?

**Comment by sbalkee** [comment]
We have this story in the current sprint. We need to test with both Auth and No-Auth scenarios, as we use Cloudfront and S3 bucket implementations respectively. @rongwang0930 found that we need to make a change for No-Auth case (index.html for S3). We have not tested this with Cloudfront yet. So, we will continue this when we start the story. Thanks @kenisteward and @aniruddhadas9 for looking into this.

**Comment by kenisteward** [comment]
@nateiam the smoke tests that are coupled with the app actually will tell you if this fails or not.  they just need to be configured to run.

**Comment by nateiam** [comment]
Verified in no-auth
In Auth, the deep links work -- but it will prompt you for auth anytime you reload or use a deep link
