### ISSUE TITLE
Build Herd-MDL from any GitHub branch

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd-mdl#13]
As a Herd-MDL OSS contributor I want to build an MDL stack from Herd-MDL code I forked and modified so I can dev/build/test contributions

NOTE - Only applies to Herd-MDL code (CFTs and scripts) -- does not need to work with customized Metastor and BDSQL code. These are handled in other stories

Acceptance Criteria
* User is able to trigger MDL build and deploy process that uses their customized MDL code
* Takes inputs: target AWS account, GitHub branch, build bucket location
  * Build bucket can be any S3 bucket
* Any pre-requisites are documented
  * see Technical Notes for AMI vs Docker

Technical Notes
* Team should determine if AMI or Docker is a better approach

**Comment by sbalkee** [comment]
1. Create Docker Image
2. Bundle/Install all dependencies into the docker image
3. Publish Docker Image
4. Parameterize AWS account specific for the build/deploy script
5. Documentation

**Comment by nateiam** [comment]
split Metastor artifact publishing into a separate issue
