### ISSUE TITLE
Execute MDLT against existing MDL stack

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd-mdl#19]
As Herd Admin I want to run MDLT on any MDL environment to ensure that MDL stack is fully functional

Acceptance Criteria
* MDLT can be configured to point to any MDL environment with minimal effort. Inputs are:  stack name, instance name, S3 bucket for results. 
  * MDLT does not require stack name and instance name to be the same
* MDLT pre-requisites are documented including:  IAM Roles, KeyPair, any network/VPC requirements
* MDLT results are in a single location and easy to retrieve 

Technical Notes
* Can run from an EC2 in any account

**Comment by sbalkee** [comment]
1. Parameter Cleanup
2. Documentation for Pre-requisites
3. Storing result sets into S3
4. Prepare and Release Code Deploy Package for MDLT
5. Script changes to get MDLT working with OSS-MDLT-Code-Package
