### ISSUE TITLE
Access Customer User accounts via LDAP

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd-mdl#20]
This is for Demo users and MDLT functional tests. 

Acceptance Criteria
* Defined scenarios work for Herd and BDSQL authorization testing

**Comment by sbalkee** [comment]
1.  Herd - Change scrty_role_cd in scrty_role table for Admin
2. Herd - Change scrty_role_cd in scrty_role table for Read-Only
3. Herd - Change scrty_role_cd in scrty_role table for Read-Write
4. Bdsql - Update Sync codebase for Admin group Authorization
5. Bdsql - Update Sync codebase for Read-Only group Authorization
6. Bdsql - Update Sync codebase for Read-Write group Authorization
7. MDLT - Herd Authorization Testing for Admin
8. MDLT - Herd Authorization Testing for Read-Only
9. MDLT - Herd Authorization Testing for Read-Write
10. MDLT - Bdsql Testing for Authorization 
11. Herd - Change Namespace permissions for Admin User
12. Herd - Change Namespace permissions for Read-Only User
13. Herd - Change Namespace permissions for Read-Write User
