### ISSUE TITLE
mdl.yml duplicate mapping key

### ISSUE THREAD

**Issue by mrperson2015** [FINRAOS/herd-mdl#86]
**Describe the bug**
It appears that in the mdl.yml file a duplicate line exists. When trying to open the YAML file in cloudformation designer I get the following error.
` 4/8/2019, 1:15:38 PM - Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 308, column 119: ... Environment, /S3/URL/Shepherd]] ^`

Lines 302 and 308 look to be identical. Once line 302 is removed the error no longer appears.

**To Reproduce**
1. Login to AWS -> Cloudformation -> Design Template
2. Open a local file and point to mdl.yml from herd-mdl 0.81.0
3. See error

**Expected behavior**
The designer should open w/o any error. Should also display the diagram.

**Details and/or logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/13457838/55750679-0f51d880-5a01-11e9-9f0f-ff717a77c06d.png)

**Additional context**
Using https://github.com/FINRAOS/herd-mdl/releases/tag/mdl-v1.4.0

**Comment by kusid** [comment]
@mrperson2015 Thanks for bringing this to our notice. Apparently, duplicate resource properties parameters in a Cloudformation template are simply ignored (or maybe it takes only the last of the duplicated key-pair). We'll push in a fix which will be available with our next release.

**Comment by kusid** [comment]
Fixed in 1.5.0
